export interface Product {
  id: string;
  name: string;
  price: number;
  image: string;
  category: string;
  description: string;
  rating: number;
  reviews: number;
  color?: string;
  size?: string;
}

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Pro Running Shoes",
    price: 129.99,
    image: "/professional-running-shoes.png",
    category: "Footwear",
    description: "High-performance running shoes with advanced cushioning",
    rating: 4.8,
    reviews: 245,
    color: "Black",
    size: "M",
  },
  {
    id: "2",
    name: "Yoga Mat Pro",
    price: 49.99,
    image: "/premium-yoga-mat.png",
    category: "Sports",
    description: "Non-slip yoga mat with carrying strap",
    rating: 4.6,
    reviews: 189,
    color: "Purple",
    size: "One Size",
  },
  {
    id: "3",
    name: "Facial Serum Luxury",
    price: 69.99,
    image: "/luxury-facial-serum.jpg",
    category: "Skincare",
    description: "Anti-aging facial serum with vitamin C",
    rating: 4.9,
    reviews: 312,
    color: "Clear",
    size: "50ml",
  },
  {
    id: "4",
    name: "Moisturizer SPF 50",
    price: 54.99,
    image: "/moisturizer-with-spf.jpg",
    category: "Skincare",
    description: "Daily moisturizer with broad spectrum protection",
    rating: 4.7,
    reviews: 278,
    color: "Beige",
    size: "100ml",
  },
  {
    id: "5",
    name: "Dumbbell Set",
    price: 199.99,
    image: "/adjustable-dumbbell-set.jpg",
    category: "Equipment",
    description: "Adjustable dumbbells 5-25 lbs",
    rating: 4.8,
    reviews: 156,
    color: "Black",
    size: "One Size",
  },
  {
    id: "6",
    name: "Lip Gloss Collection",
    price: 34.99,
    image: "/lip-gloss-collection.jpg",
    category: "Makeup",
    description: "Set of 6 premium lip glosses",
    rating: 4.5,
    reviews: 201,
    color: "Rose",
    size: "One Size",
  },
  {
    id: "7",
    name: "Sports Water Bottle",
    price: 39.99,
    image: "/insulated-sports-water-bottle.jpg",
    category: "Accessories",
    description: "Insulated stainless steel water bottle",
    rating: 4.7,
    reviews: 234,
    color: "Silver",
    size: "750ml",
  },
  {
    id: "8",
    name: "Face Mask Set",
    price: 44.99,
    image: "/premium-face-mask-set.jpg",
    category: "Skincare",
    description: "Set of 3 hydrating face masks",
    rating: 4.8,
    reviews: 198,
    color: "White",
    size: "One Size",
  },
  {
    id: "9",
    name: "Sports Backpack",
    price: 89.99,
    image: "/sports-backpack.jpg",
    category: "Accessories",
    description: "Water-resistant sports backpack with laptop compartment",
    rating: 4.6,
    reviews: 142,
    color: "Black",
    size: "One Size",
  },
  {
    id: "10",
    name: "Athletic Socks Pack",
    price: 29.99,
    image: "/athletic-socks.jpg",
    category: "Accessories",
    description: "Pack of 6 moisture-wicking athletic socks",
    rating: 4.7,
    reviews: 198,
    color: "White",
    size: "One Size",
  },
  {
    id: "11",
    name: "Training Sneakers",
    price: 119.99,
    image: "/training-sneakers.jpg",
    category: "Footwear",
    description: "Professional training shoes for gym and cross-training",
    rating: 4.8,
    reviews: 267,
    color: "Navy",
    size: "L",
  },
  {
    id: "12",
    name: "Resistance Bands Set",
    price: 24.99,
    image: "/resistance-bands.jpg",
    category: "Equipment",
    description: "Set of 5 resistance bands with carrying bag",
    rating: 4.6,
    reviews: 189,
    color: "Multi",
    size: "One Size",
  },
  {
    id: "13",
    name: "Eye Shadow Palette",
    price: 44.99,
    image: "/eyeshadow-palette.jpg",
    category: "Makeup",
    description: "Professional 24-color eyeshadow palette",
    rating: 4.9,
    reviews: 324,
    color: "Multi",
    size: "One Size",
  },
  {
    id: "14",
    name: "Foundation Brush Set",
    price: 39.99,
    image: "/foundation-brushes.jpg",
    category: "Makeup",
    description: "Professional makeup brush set with case",
    rating: 4.7,
    reviews: 156,
    color: "Black",
    size: "One Size",
  },
  {
    id: "15",
    name: "Hair Care Bundle",
    price: 59.99,
    image: "/hair-care-bundle.jpg",
    category: "Beauty",
    description: "Premium shampoo, conditioner, and hair mask",
    rating: 4.8,
    reviews: 221,
    color: "Brown",
    size: "One Size",
  },
  {
    id: "16",
    name: "Leather Sports Shoes",
    price: 149.99,
    image: "/leather-sports-shoes.jpg",
    category: "Footwear",
    description: "Premium leather casual sports shoes",
    rating: 4.7,
    reviews: 203,
    color: "Brown",
    size: "XL",
  },
];

export const products = PRODUCTS;
